package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/rs/zerolog/log"
)

type subspace struct {
	name    string
	comment string
}

func genFileDocs(filename string) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	curDoc := ""

	ast.Inspect(f, func(n ast.Node) bool {
		switch t := n.(type) {
		case *ast.GenDecl:
			curDoc = t.Doc.Text()
		case *ast.TypeSpec:
			if strings.HasSuffix(t.Name.Name, "Directory") {
				fmt.Println("###", t.Name.Name)
				fmt.Println("")
				if curDoc != "" {
					fmt.Println(curDoc)
					fmt.Println("")
				}
			}
		case *ast.StructType:
			tbl := table.NewWriter()
			tbl.SetOutputMirror(os.Stdout)
			tbl.AppendHeader(table.Row{"Field", "Key", "Value", "Notes"})

			for _, field := range t.Fields.List {
				selector, ok := field.Type.(*ast.SelectorExpr)
				if !ok {
					log.Warn().Type("type", field.Type).Msg("Not selector expr")
					continue
				}
				typeS := selector.Sel.String()
				if typeS != "Subspace" {
					log.Warn().Str("type", typeS).Msg("Not subspace field")
					continue
				}

				var keyS, valueS string
				docLines := strings.Split(field.Doc.Text(), "\n")
				doc := ""
				for _, line := range docLines {
					if line == "" {
						continue
					} else if strings.HasPrefix(line, "key: ") {
						keyS = "`" + line[5:] + "`"
						continue
					} else if strings.HasPrefix(line, "value: ") {
						valueS = "`" + line[7:] + "`"
						continue
					}
					doc += line + "\n"
				}

				name := "`" + field.Names[0].String() + "`"
				tbl.AppendRow(table.Row{name, keyS, valueS, doc})
			}

			if tbl.Length() > 0 {
				tbl.RenderMarkdown()
				fmt.Println()
			}
		}
		return true
	})
}
func main() {
	fmt.Println(`AUTOGENERATED FILE DO NOT EDIT

This file contains autogenerated "schema" for Babbleserv's FoundationDB keyvalues.`)

	fmt.Println("")
	fmt.Println("")
	fmt.Println("# Accounts Database")
	fmt.Println("")
	filepath.Walk("internal/databases/accounts", func(path string, info fs.FileInfo, err error) error {
		if strings.HasSuffix(info.Name(), ".go") {
			genFileDocs(path)
		}
		return nil
	})

	fmt.Println("")
	fmt.Println("# Media Database")
	fmt.Println("")
	filepath.Walk("internal/databases/media", func(path string, info fs.FileInfo, err error) error {
		if strings.HasSuffix(info.Name(), ".go") {
			genFileDocs(path)
		}
		return nil
	})

	fmt.Println("")
	fmt.Println("# Rooms Database")
	fmt.Println("")
	filepath.Walk("internal/databases/rooms", func(path string, info fs.FileInfo, err error) error {
		if strings.HasSuffix(info.Name(), ".go") {
			genFileDocs(path)
		}
		return nil
	})

	fmt.Println("")
	fmt.Println("# System Database")
	fmt.Println("")
	filepath.Walk("internal/databases/system", func(path string, info fs.FileInfo, err error) error {
		if strings.HasSuffix(info.Name(), ".go") {
			genFileDocs(path)
		}
		return nil
	})

	fmt.Println("")
	fmt.Println("# Transient Database")
	fmt.Println("")
	filepath.Walk("internal/databases/transient", func(path string, info fs.FileInfo, err error) error {
		if strings.HasSuffix(info.Name(), ".go") {
			genFileDocs(path)
		}
		return nil
	})
}
