FROM golang:1.24.3-bookworm
WORKDIR /build

ARG COMMIT_HASH
ENV COMMIT_HASH=${COMMIT_HASH}

# Install FoundationDB client + bindings
RUN wget https://github.com/apple/foundationdb/releases/download/7.3.71/foundationdb-clients_7.3.71-1_amd64.deb && \
    dpkg -i foundationdb-clients_7.3.71-1_amd64.deb
# Install & setup fdbserver
RUN wget https://github.com/apple/foundationdb/releases/download/7.3.71/foundationdb-server_7.3.71-1_amd64.deb && \
    dpkg -i foundationdb-server_7.3.71-1_amd64.deb

RUN apt-get update && apt-get install -y libolm-dev libolm3

# Setup go dependencies
COPY go.mod go.sum /build/
# COPY external /build/external
RUN go mod download

COPY . /build
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -o babbleserv ./cmd/babbleserv
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -o babbleserv-cli ./cmd/babbleserv-cli

COPY docker/complement.sh /complement.sh
COPY docker/complement-config.yaml /complement-config.yaml
RUN chmod +x /complement.sh
ENTRYPOINT ["/complement.sh"]
EXPOSE 8008
EXPOSE 8448
