package federation

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"github.com/matrix-org/gomatrixserverlib/spec"
	"github.com/rs/zerolog/hlog"
	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/event"
	"maunium.net/go/mautrix/id"

	"github.com/beeper/babbleserv/internal/databases/rooms"
	"github.com/beeper/babbleserv/internal/middleware"
	"github.com/beeper/babbleserv/internal/types"
	"github.com/beeper/babbleserv/internal/util"
)

func sendEventErrorResponse(w http.ResponseWriter, r *http.Request, err error) {
	if errors.Is(err, rooms.ErrAuthStage4) {
		// Stage4 errors happen when the events own auth events don't allow it, so this is an
		// invalid input param.
		util.ResponseErrorMessageJSON(w, r, mautrix.MInvalidParam, err.Error())
		return
	}
	// Stage5 errors happen based on the events prev_events (after passing stage4), so should
	// be treated as an authorization error.
	util.ResponseErrorMessageJSON(w, r, mautrix.MForbidden, err.Error())
}

func (f *FederationRoutes) makeMembershipEventForOtherServer(
	w http.ResponseWriter,
	r *http.Request,
	membership event.Membership,
	checkRequestVersions bool,
) {
	roomID := util.RoomIDFromRequestURLParam(r, "roomID")
	remoteUserID := util.UserIDFromRequestURLParam(r, "userID")

	otherServer := remoteUserID.Homeserver()
	if otherServer == f.config.ServerName {
		util.ResponseErrorMessageJSON(
			w, r, mautrix.MForbidden,
			"UserID is from this server, cannot make federated event",
		)
	} else if otherServer != middleware.GetRequestServer(r) {
		util.ResponseErrorMessageJSON(
			w, r, mautrix.MForbidden,
			"UserID does not match requesting server origin",
		)
	}

	room, err := f.db.Rooms.GetRoom(r.Context(), roomID)
	if err != nil {
		util.ResponseErrorUnknownJSON(w, r, err)
		return
	} else if room == nil {
		util.ResponseErrorMessageJSON(w, r, mautrix.MNotFound, "Room not found")
		return
	} else if checkRequestVersions {
		if !slices.Contains(r.URL.Query()["ver"], room.Version) {
			util.ResponseErrorMessageJSON(w, r, mautrix.MInvalidParam, "Room version not supported")
			return
		}
	}

	content := map[string]any{
		"membership": membership,
	}

	// If possible grab the users profile from the requesting server
	// TODO: check if we have the profile locally (uh, where)
	if f.config.Federation.FetchProfileForMemberEvents {
		if profileResp, err := f.fclient.LookupProfile(
			r.Context(),
			spec.ServerName(f.config.ServerName),
			spec.ServerName(otherServer),
			remoteUserID.String(),
			"",
		); err != nil {
			hlog.FromRequest(r).
				Warn().
				Err(err).
				Msg("Error fetching profile information when making remote join")
		} else {
			if profileResp.DisplayName != "" {
				content["displayname"] = profileResp.DisplayName
			}
			if profileResp.AvatarURL != "" {
				content["avatar_url"] = profileResp.AvatarURL
			}
		}
	}

	sKey := remoteUserID.String()
	partialEv := types.NewPartialEvent(roomID, event.StateMember, &sKey, remoteUserID, content)

	evs, rejected, err := f.db.Rooms.PrepareLocalEvents(r.Context(), roomID, []*types.PartialEvent{partialEv})
	if err != nil {
		util.ResponseErrorUnknownJSON(w, r, err)
		return
	} else if len(rejected) > 0 {
		sendEventErrorResponse(w, r, rejected[0].Error)
		return
	}
	ev := evs[0]

	// Drop the signatures/hashes - the joining server may alter the content
	// before they call send_join and these should not be included.
	// ev.Hashes = make(map[string]string)
	clear(ev.Hashes)
	clear(ev.Signatures)

	util.ResponseJSON(w, r, http.StatusOK, struct {
		Event       *types.Event `json:"event"`
		RoomVersion string       `json:"room_version"`
	}{ev, ev.RoomVersion})
}

func (f *FederationRoutes) sendMembershipEventFromOtherServer(
	w http.ResponseWriter,
	r *http.Request,
	membership event.Membership,
	getResponseBeforeSend func(id.RoomID) (any, error),
) {
	var ev types.Event
	if err := json.NewDecoder(r.Body).Decode(&ev); err != nil {
		util.ResponseErrorJSON(w, r, mautrix.MNotJSON)
		return
	}

	if ev.Type != event.StateMember {
		util.ResponseErrorMessageJSON(w, r, mautrix.MInvalidParam, "Event type is not m.room.member")
		return
	} else if ev.StateKey == nil {
		util.ResponseErrorMessageJSON(w, r, mautrix.MInvalidParam, "State key is not set")
		return
	} else if ev.Membership() != membership {
		util.ResponseErrorMessageJSON(w, r, mautrix.MInvalidParam, "Membership is incorrect")
		return
	}

	roomID := util.RoomIDFromRequestURLParam(r, "roomID")

	ev.RoomID = roomID
	ev.ID = util.EventIDFromRequestURLParam(r, "eventID")
	// Event was generated by us, and will be sent over federation
	ev.Local = true

	// Lookup room, if we know about it, we need *a* room version here
	room, err := f.db.Rooms.GetRoom(r.Context(), roomID)
	if err != nil {
		util.ResponseErrorUnknownJSON(w, r, err)
		return
	} else if room != nil {
		ev.RoomVersion = room.Version
	} else {
		ev.RoomVersion = f.config.Rooms.DefaultVersion // TODO: what do we do here?
	}

	// Veriy the event is signed by the requesting HS
	verifyErr, err := util.VerifyEvent(r.Context(), &ev, middleware.GetRequestServer(r), f.keyStore)
	if err != nil {
		util.ResponseErrorUnknownJSON(w, r, err)
		return
	} else if verifyErr != nil {
		util.ResponseErrorMessageJSON(w, r, mautrix.MInvalidParam, verifyErr.Error())
		return
	}

	var response any = util.EmptyJSON
	if getResponseBeforeSend != nil {
		response, err = getResponseBeforeSend(roomID)
		if err != nil {
			util.ResponseErrorUnknownJSON(w, r, err)
			return
		}
	}

	isInRoom, err := f.db.Rooms.IsServerJoinedRoom(r.Context(), f.config.ServerName, roomID)
	if err != nil {
		util.ResponseErrorUnknownJSON(w, r, err)
		return
	} else if !isInRoom {
		// We don't have the room - there's two cases where this might happen:
		// - remote user is rejecting an invite sent from a local user who has now left
		// - remote user is rescinding their own invite and we've never been in the room
		if membership != event.MembershipLeave {
			// Only leave memberships are valid here
			util.ResponseErrorMessageJSON(w, r, mautrix.MNotFound, "Room not found, sent membership is not leave")
			return
		}
		targetUserMembership, err := f.db.Rooms.GetUserMembership(r.Context(), id.UserID(*ev.StateKey), roomID)
		if err != nil {
			util.ResponseErrorUnknownJSON(w, r, err)
			return
		} else if targetUserMembership == nil || targetUserMembership.Membership != event.MembershipInvite {
			// Unknown room leaves are only valid if the target user is currently invited
			util.ResponseErrorMessageJSON(w, r, mautrix.MNotFound, "Room not found, current membership is not invite")
			return
		}
		targetUserMembershipEv, err := f.db.Rooms.GetEvent(r.Context(), targetUserMembership.EventID)
		if err != nil {
			util.ResponseErrorUnknownJSON(w, r, err)
			return
		} else if targetUserMembershipEv == nil {
			panic(fmt.Errorf("missing membership event: %s", targetUserMembership.EventID))
		}
		if targetUserMembershipEv.Sender.Homeserver() == f.config.ServerName {
			// Invite is from a local user (reject)
		} else if targetUserMembershipEv.Sender == ev.Sender {
			// Invite was sent by the remote user (rescind)
		} else {
			util.ResponseErrorMessageJSON(w, r, mautrix.MNotFound, "Room not found, not an invite reject or rescind")
			return
		}
	}

	if !isInRoom {
		if err := f.db.Rooms.SendFederatedOutlierMembershipEvent(r.Context(), &ev); err != nil {
			util.ResponseErrorUnknownJSON(w, r, err)
			return
		}
	} else {
		if res, err := f.db.Rooms.SendFederatedEvents(r.Context(), roomID, []*types.Event{&ev}, rooms.SendFederatedEventsOptions{}); err != nil {
			util.ResponseErrorUnknownJSON(w, r, err)
			return
		} else if len(res.Rejected) > 0 {
			sendEventErrorResponse(w, r, res.Rejected[0].Error)
			return
		}
	}

	util.ResponseJSON(w, r, http.StatusOK, response)
}
